### ISSUE TITLE
Update the github URL to point to RTD

### ISSUE THREAD

**Issue by choldgraf** [minrk/thebelab#108]
The github title url still points to the gh-pages version of the docs:

---
![image](https://user-images.githubusercontent.com/1839645/51553229-28e27b80-1e27-11e9-83b5-d682ccc6413b.png)
---

I don't believe I can change this, so just flagging it for you all :-)

**Comment by nthiery** [comment]
I was about to do it, but actually don't have permissions. I thought I have.
Just for quick reference, the desired URL is https://thebelab.readthedocs.io .

Very nice to have this on RTD, and active, btw!

**Comment by choldgraf** [comment]
Hmmm, the way I was doing it locally was with this line:

https://github.com/minrk/thebelab/blob/master/docs/conf.py#L190

but maybe readthedocs is a bit more restrictive about what you can put in the `_build` directory? Another way to do this would be to define that directory as static files, and then link to the HTML from `_static`.

**Comment by choldgraf** [comment]
pinging @minrk , since I think he's the only one that can do this...

**Comment by minrk** [comment]
Updated. Thanks!
