### ISSUE TITLE
Specify working directory in binder options

### ISSUE THREAD

**Issue by joergbrech** [minrk/thebelab#114]
I have a github repository with subdirectories. In these subdirectories I have both thebe-enabled sites and some additional code, say `subdir/mycode.py`. When I use thebelab, binder always starts in the root directory of the repository, so that I cannot use the code in `subdir/mycode.py` which would be really convenient.

Is there a way to specify the (relative) working directory via the binderOptions? I have tried adding `?filepath=` to the `binderOptions.ref` string, which did not work.

I am not a web developer and don't know javascript, but from the console output:

```
Binder: Launching server...
thebelab.js:352:8
Binder phase: ready thebelab.js:340:8
Binder: server running at https://hub.mybinder.org/user/joergbrech-mode--und-simulation-fvgx3ovy/
thebelab.js:352:8
Starting WebSocket: wss://hub.mybinder.org/user/joergbrech-mode--und-simulation-fvgx3ovy/api/kernels/212d9d62-a028-4f36-ba61-905379ff7153 default.js:61
Kernel: connected (212d9d62-a028-4f36-ba61-905379ff7153) default.js:1432 
```
it seems like we could just request a binder server at `https://hub.mybinder.org/user/joergbrech-mode--und-simulation-fvgx3ovy/SUBDIR`, where `SUBDIR` could be specified via `binderOptions.workingDirectory` for instance...does that make any sense?

This issue is related to jupyter/jupyter-book#107.

**Comment by joergbrech** [comment]
Navigating to `https://hub.mybinder.org/user/joergbrech-mode--und-simulation-fvgx3ovy/tree/subdir` opens jupyter notebook in the desired subdirectory `subdir` of my github repository. 

So it seems like the baseUrl could be appended by `'tree/'` + `binderOptions.workingDir` in the following line to get this to work?

https://github.com/minrk/thebelab/blob/ae16b142ebfc8eb5c1394e2b2302bda704988979/src/thebelab.js#L402

**Comment by choldgraf** [comment]
ah very nice, ok if I have a moment to give this a shot I will try soon!

**Comment by hugokerstens** [comment]
I would like to use this feature as well.
I was looking for ways on how to implement this. I'm inexperienced with Jupyter, but isn't it as simple as just swapping Kernel with Session, and then return `session.kernel`?

https://github.com/minrk/thebelab/blob/e50059b6a9c7018b5ba880e91f18e27c45df020a/src/thebelab.js#L307-L314

Then you can add `path` to `kernelOptions` in your config, and you should be good to go.

**Comment by joergbrech** [comment]
There has been a regression of this. Currently, when running thebe from a jupyter-book, the session starts in the root directory rather than the directory of the jupyter notebook. See also https://github.com/executablebooks/jupyter-book/issues/107.

**Comment by choldgraf** [comment]
Can you open a new issue to detail the problems, your current set-up, etc? Either here or in jupyter-book?

**Comment by joergbrech** [comment]
Done! https://github.com/executablebooks/jupyter-book/issues/1304 😃
