### ISSUE TITLE
codeMirrorConfig

### ISSUE THREAD

**Issue by sharypovandrey** [minrk/thebelab#115]
Hello! I tried to use codeMirrorConfig settings but it does not have affect.
Am I doing something wrong?
```
        codeMirrorConfig: {
          lineNumbers: true,
          minHeight: "600px"
        }
```

**Comment by choldgraf** [comment]
I _believe_ that this won't be available until a new release gets made for thebelab :-/

**Comment by choldgraf** [comment]
(somebody on the thebelab project should confirm that though :-) )

**Comment by minrk** [comment]
Yup, 0.4 is published with this feature just now
