### ISSUE TITLE
Inputs

### ISSUE THREAD

**Issue by sharypovandrey** [minrk/thebelab#116]
Hello!
I want to use python's `input()` function. Is there a way to use it in Thebelab?
If to consider Jupyter notebook, after input function the input field appears.
Just wondering about the same in CodeMirror cell

**Comment by minrk** [comment]
I think we'll need to figure out how JupyterLab adds that handler and make sure it's hooked up.

**Comment by sharypovandrey** [comment]
I found that it works now

**Comment by minrk** [comment]
thanks for updating. Could have been fixed when we updated the jupyterlab dependency.
