### ISSUE TITLE
Codemirror syntax highlight seems to be off in the new version

### ISSUE THREAD

**Issue by choldgraf** [minrk/thebelab#126]
From [this issue](https://github.com/jupyter/jupyter-book/issues/151) originally spotted in jupyter-book

> It seems like syntax highlighting is broken since the update to thebelab 0.4.0.
>
> https://github.com/jupyter/jupyter-book/blob/dde0aab8faa335172c68643718232c6210b1f6ce/jupyter_book/book_template/_includes/js/thebelab.html#L18
>
> See here for instance: https://jupyter.org/jupyter-book/features/notebooks.html (press the Thebelab button)

Is anybody else experiencing this as well? I wonder if it's related to the codemirror theme PR?

**Comment by sharypovandrey** [comment]
Hi @minrk! Is it a Codemirror issue? For me and configs doesnt work when I specify it in ThebeLab configs

**Comment by Fdango** [comment]
@choldgraf hey,Is there any new way of thinking about this problem?

**Comment by Fdango** [comment]
@choldgraf It is because thebelab is configured in codemirror mismatch that we can customize the introduction of codemirror style first.
`const mode = $element.data("language") || "text/x-python";`

**Comment by sergeyepimakhov** [comment]
Seems it will be solved in #171

**Comment by minrk** [comment]
Released 0.5.1 with this fix

**Comment by ChangezKhan** [comment]
I think this issue still persists with the newer 0.5.1 release. Even the [example](https://thebelab.readthedocs.io/en/latest/howto/cm_customize.html#customizing-codemirror) provided on the official page doesn't work.
Kindly find the more detailed information here: https://stackoverflow.com/questions/59397261/how-to-style-input-boxuse-codemirror-of-thebelab
Kindly let me know how to fix this issue.
