### ISSUE TITLE
Running ThebeLab Against A Local Kernel

### ISSUE THREAD

**Issue by psychemedia** [minrk/thebelab#136]
Picking up on https://github.com/jupyter/jupyter-book/issues/199 .

At the moment, code execution via ThebeLab is handled by spawning a MyBinder environment within which code is executed.

When an HTML page is published on a local machine which is a also running a Jupyter service, it would be useful if ThebeLab could execute code in a kernel launched via the local server, rather than one launched via a Binderhub.

**Comment by akhmerov** [comment]
This is already [possible](https://thebelab.readthedocs.io/en/latest/_static/local.html), or do you mean something beyond that?

**Comment by psychemedia** [comment]
Ah, thanks... my bad. Will give that a go...
