### ISSUE TITLE
Missing tag for 0.4.0

### ISSUE THREAD

**Issue by SylvainCorlay** [minrk/thebelab#139]
Version 0.4.0 was released on npm but the tag is missing on the repository.

**Comment by choldgraf** [comment]
good catch - anything that needs to be done to cut a release other than a `git tag` and then putting the release on github? It doesn't look like many fancy things happen w/ changelog etc

**Comment by SylvainCorlay** [comment]
Thebelabbis published on npm.

**Comment by minrk** [comment]
thanks, forgot `git push --tags` on the last release. It's there now.
