### ISSUE TITLE
Docs not showing widget

### ISSUE THREAD

**Issue by vidartf** [minrk/thebelab#158]
Trying the demo on the [documentation frontpage](https://thebelab.readthedocs.io/en/latest/), I get this result:

![image](https://user-images.githubusercontent.com/510760/61800968-e88ba680-ae25-11e9-85b5-484776d94ef1.png)

It seems to correctly connect to the kernel (it gets an output), but the widget is simply not rendering. No clear errors in the JS console I'm afraid (no entries after "Kernel: Connected", after which the run button was clicked).

**Comment by minrk** [comment]
`%matplotlib inline` is needed. I'm pretty sure this isn't supposed to be the case with current IPython and matplotlib, so there must be a regression somewhere. This isn't a thebelab issue, but one of negotiation between matplotlib and IPython about enabling inline figures by default.

**Comment by SylvainCorlay** [comment]
You may also try with `ipympl`.

**Comment by vidartf** [comment]
Just to be clear, I'm not having a problem with use, I just thought having the demo in the docs not working is a bit of a bad look. 😉
