### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by choldgraf** [minrk/thebelab#162]
Over in jupyter book (https://github.com/jupyter/jupyter-book/pull/189) we are waiting on a new release so that we can customize the path where the kernel starts (from #131). We haven't had a release since March, can we cut a new one? Or alternatively is there a way to load the JS from master from a CDN somewhere?

**Comment by minrk** [comment]
0.5.0 and 0.5.1 have been released. Next time, let's walk through making a release so this doesn't block on me anymore.

**Comment by choldgraf** [comment]
@minrk if you wanna sit down with me to show me how, then I can also write out some release instructions as well (related to #175 )

**Comment by minrk** [comment]
Yeah, let's do that. Thanks!
