### ISSUE TITLE
Initialization Cells in Jupyter Books

### ISSUE THREAD

**Issue by chrispyles** [minrk/thebelab#164]
Is there a way when using Thebelab in a Jupyter Book to have certain hidden cells run first as initialization cells (e.g. cells that load dependencies). I usually like to keep these hidden in textbooks so this feature would be very useful!

**Comment by choldgraf** [comment]
Ah I just realized that I'd asked about this several months back already :-)

here's the relevant issue:

https://github.com/minrk/thebelab/issues/94

I think in Jupyter Book, we could play around with the fix suggested there (to add javascript that listens for the thebelab event, and when it hears it, runs any cell that matches some kind of tag query).

So I think this *could* be a JB fix and not require changes in thebelab...

**Comment by choldgraf** [comment]
Let's close this one since I think it's covered in #94 and will hopefully be closable soon!
