### ISSUE TITLE
IRkernel not working with ThebeLab > 0.4.0

### ISSUE THREAD

**Issue by RaoOfPhysics** [minrk/thebelab#177]
Hi Min,

It seems that ThebeLab versions 0.5.0 and onwards don't use the IRkernel (from [binder-examples/r](https://github.com/binder-examples/r) for example). Here's an example page with the latest version: https://cern.ch/achintya/thebelab-latest-test.html

The `R` code worked with the following:

```html
<script src="https://unpkg.com/thebelab@0.4.0/lib/index.js"></script>
```

But changing `0.4.0` to `0.5.0` (or `latest`) gives this error:

```python
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-33599bed5b8e> in <module>
----> 1 x <- 3
      2 y <- 8
      3 (x*y)

NameError: name 'x' is not defined
```

**Comment by RaoOfPhysics** [comment]
Hi Min,

I hope all is well with you.

Have you had a chance to look at this?

I’m trying to integrate ThebeLab with my blog and at the moment:

- `v0.3.3` does not support GitLab as a source for the Binder configs
- `v0.4.0` breaks the JS that renders the footer for the Hugo theme I’m using
- `v0.5.0` onwards does not work with the IRkernel

So I am kind of stuck. :D

Thank you! :)

**Comment by choldgraf** [comment]
hmm - it seems like the code that would be breaking this would be somewhere around: https://github.com/minrk/thebelab/blob/8b6d82c24727ae67685c89bea99f38031df12ea1/src/thebelab.js#L306 though I'm not quite sure because I don't understand the jupyterlab API that much :-/

**Comment by choldgraf** [comment]
actually, I think what's going wrong is that the kernel isn't set using the `data-language` attribute. It's set with the Thebelab configuration activation. Try adding

```
kernelOptions:
    kernelName: "{kernel_name}",
```

to the config

**Comment by RaoOfPhysics** [comment]
That works, @choldgraf! :D Thank you so very much!

(And apologies for not replying sooner; I haven’t checked GitHub in a few days.)

**Comment by choldgraf** [comment]
wohoo! ok I'll close this as I think it's fixed
