### ISSUE TITLE
basic widgets not working

### ISSUE THREAD

**Issue by minrk** [minrk/thebelab#72]
cc @SylvainCorlay 

basic widgets don't seem to be working right now:

```python
from ipywidgets import *
IntSlider(5)
```

gives `Error displaying widget`. js console shows:

> TypeError: this.handle.stop is not a function. (In 'this.handle.stop(1,1)', 'this.handle.stop' is undefined)

<details>

```
TypeError: this.handle.stop is not a function. (In 'this.handle.stop(1,1)', 'this.handle.stop' is undefined)
_refreshValue — slider.js:654
https://unpkg.com/thebelab
_refresh — slider.js:106
https://unpkg.com/thebelab
_create — slider.js:97
https://unpkg.com/thebelab
_createWidget — widget.js:340
https://unpkg.com/thebelab
https://unpkg.com/thebelab
each — jquery.slim.js:354
https://unpkg.com/thebelab
render — widget_int.js:127
https://unpkg.com/thebelab
promiseReactionJob
```

</details>

Maybe a version mismatch?

Reported by @lukasheinrich

**Comment by SylvainCorlay** [comment]
I am afk but was just testing on my phone. The Label appears to work but not the slider.

I cannot troubleshoot right now. Could it be an issue with the jqueryui version? Cc @jasongrout

**Comment by lukasheinrich** [comment]
is this the property that `this.handle.stop` refers to?
https://github.com/jupyter-widgets/ipywidgets/blob/08ac3244d84c79b6943a3d2792b076f71967fb04/packages/controls/src/widget_int.ts#L109

**Comment by SylvainCorlay** [comment]
Yes, The slider is the only widget making use of jqueryui and "stop" refers to an event of the jqueryui slider handle.

**Comment by SylvainCorlay** [comment]
We need to check if there was a breaking change in jqueryui and the requirement in package.json for @jupyter-widgets/controls

**Comment by SylvainCorlay** [comment]
@minrk I have opened a PR fixing this. The issue came from the use of the "slim" version of jquery.

**Comment by lukasheinrich** [comment]
great! works on minrk.github.io now that the package is updated on npm. Thanks!
<img width="452" alt="screenshot" src="https://user-images.githubusercontent.com/2318083/44006100-89967360-9e7e-11e8-90aa-112f764f7f53.png">

**Comment by lukasheinrich** [comment]
actually `interact(...)` seems to still break, while the `IntSlider` works. Tested on minrk.github.io and locally with an updated 0.3.3 

<img width="690" alt="screenshot" src="https://user-images.githubusercontent.com/2318083/44006248-5d96fd7c-9e81-11e8-848b-d9dadc4a9c8d.png">

**Comment by SylvainCorlay** [comment]
Interact will need some work with the `Output` widget, which is a bit more involved.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay thanks for finding and fixing it! Published 0.3.3 with this (and your restart button).

Thanks @minrk I will push out an example with C++ tomorrow :)

**Comment by lukasheinrich** [comment]
@SylvainCorlay can you give some detail what kind of work will be needed, we would like to contribute to making sliders etc work.

**Comment by lukasheinrich** [comment]
thanks @SylvainCorlay. I see an output widget being implemented here https://github.com/minrk/thebelab/blob/master/src/output.js . Does this just need to be extended?
