### ISSUE TITLE
make it possible to auto-execute some cells according to a query

### ISSUE THREAD

**Issue by choldgraf** [minrk/thebelab#94]
Sometimes we hide the import block of notebooks in the rendered web page to improve the tidiness of the page. However, if you're using something like thebelab, this means that users don't have the ability to actually run that code block and thus the code won't run. Is it possible to auto-run some cells (e.g. ones that are hidden) according to a jquery match? (e.g. `pre.run`)? This might be useful for this use case!

**Comment by minrk** [comment]
You ought to be able to do this if you listen for the kernel-request event. Something like:

```javascript
thebelab.events.on("request-kernel")((kernel) => {
    # kernel might actually be a promise for a kernel here?
    return kernel.requestExecute({code: "import numpy"})
});
```

but a scheme for doing it declaratively makes sense.

**Comment by choldgraf** [comment]
Nice - then to me this feels like documentation, followed by letting people experiment, and then later revisit if this makes sense to do as a built-in to thebelab, WDYT?

**Comment by minrk** [comment]
> WDYT?

👌

**Comment by choldgraf** [comment]
See https://github.com/jupyter/jupyter-book/pull/352 for an implementation of this, in that case I'm actually just simulating "click" events on the thebelab buttons so that the cells have their outputs etc populated
