### ISSUE TITLE
Improving the text editor for live cells w/ CodeMirror

### ISSUE THREAD

**Issue by choldgraf** [minrk/thebelab#95]
A nice feature of the Juniper package is that it replaces code cells with `CodeMirror` cells that have syntax highlighting, themeing, etc. It seems that the code they use for creating codemirror cells is here:

https://github.com/ines/juniper/blob/master/src/index.js#L135

Just flagging this in case it's in-scope and would be of value to thebelab

**Comment by nthiery** [comment]
Thanks for the pointer; I had not seen Juniper on my radar. In https://github.com/ines/juniper/issues/2, I asked about a potential  Juniper/Thebelab convergence.

**Comment by choldgraf** [comment]
I think a convergence would be great - my feeling w/ that project is that they liked thebelab's experience, wanted something slightly different for a specific use-case, and also wanted an excuse to learn a bit about the lab API, so perhaps they'd be open to working together a bit. It does seem like there's a lot of overlap

**Comment by minrk** [comment]
I'm a little confused. thebelab also [creates CodeMirror instances](https://github.com/minrk/thebelab/blob/c70aa40356e2918b990786da10f08fd889a20e29/src/thebelab.js#L226) for cells with syntax highlighting, etc.. Is the issue about what CodeMirror options are enabled or not?

**Comment by minrk** [comment]
It could certainly be something wrong in thebelab not setting itself up right. Where is this happening? Do you see any errors in the js console? What's the highlight language?

**Comment by choldgraf** [comment]
for an example see here: https://predictablynoisy.com/jupyter-book/features/notebooks

(click the "thebelab" button)

**Comment by Miniland1333** [comment]
Could it be that you aren't adding a data-language attribute to your code cells?
In the thebelab examples, it has a data-language attribute in order to indicate what syntax highlighter to use:
`<pre data-executable="true" data-language="python">print("Hello!")</pre>`

Based on the source code of that page, I would recommend adding code around line 169 of the notebooks.html file to correct this issue!
```javascript
// Find all code cells, replace with Thebelab interactive code cells
const codeCells = document.querySelectorAll('.input_area pre')
codeCells.forEach((codeCell, index) => {
       const id = codeCellId(index)
       codeCell.setAttribute('data-executable', '')
       codeCell.setAttribute('data-language', 'python') //added line
});
```

**Comment by choldgraf** [comment]
This totally fixed my problem @Miniland1333 , thanks for letting me know :-)

**Comment by slel** [comment]
Should there be a word about that on [Thebelab's homepage](https://minrk.github.io/thebelab/)?

**Comment by choldgraf** [comment]
@slel I added in a short mention of this in #100 though that documentation hasn't gone live yet
