### ISSUE TITLE
Codemirror default language should be "python" not "python3"

### ISSUE THREAD

**Issue by choldgraf** [minrk/thebelab#96]
I noticed that my code cells weren't being highlighted when I didn't specify `data-language`. I *think* that is because currently thebelab defaults to "python3"

https://github.com/minrk/thebelab/blob/c70aa40356e2918b990786da10f08fd889a20e29/src/thebelab.js#L225

but, I think instead this should just be "python".

**Comment by minrk** [comment]
ah, good catch. Will investigate. I thought python and python3 were listed as separate languages in codemirror, but that info may be a few years out of date.
